core/accounts/api/v1/urls.py
from django.urls import path
from .views import RegisterApiView
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)


urlpatterns = [
    path("register/", RegisterApiView.as_view(), name="register"),
    path("token/login", ObtainAuthToken.as_view(), name="token_obtain"),
    path("jwt/create/", TokenObtainPairView.as_view(), name="jwt_obtain_pair"),
    path("jwt/refresh/", TokenRefreshView.as_view(), name="jwt_refresh"),
    path("jwt/verify/", TokenVerifyView.as_view(), name="jwt_verify"),
]

core/accounts/urls.py
from django.urls import path, include
from .views import SignInView, SignUpView

from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    path("signin/", SignInView.as_view(), name="signin"),
    path("logout", LogoutView.as_view(next_page="signin/"), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("api/v1/", include("accounts.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import include, path

# api documenting
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


# app urls
urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("todo.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

core/accounts/models.py
# from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, AbstractUser
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.base_user import BaseUserManager


class UserManager(BaseUserManager):
    """Custom user model manager where username is the unique identifier for authentication."""

    def create_user(self, username, password, **extra_fields):
        """Create and save a User with the given username and password."""
        if not username:
            raise ValueError(_("The username must be set"))
        username = username.lower()
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model."""

    username = models.CharField(
        _("username"), max_length=150, unique=True
    )  # Add max_length
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = []

    objects = UserManager()

    groups = models.ManyToManyField(
        "auth.Group",
        related_name="accounts_user_set",  # Add related_name to avoid clash
        blank=True,
    )

    user_permissions = models.ManyToManyField(
        "auth.Permission",
        related_name="accounts_user_set",  # Add related_name to avoid clash
        blank=True,
    )

    def __str__(self):
        return self.username

core/accounts/api/v1/views.py
from rest_framework.response import Response
from rest_framework import status
from rest_framework import generics

# from rest_framework.permissions import IsAuthenticated
# from django.shortcuts import get_object_or_404
from .serializers import (
    RegisterSerializer,
)


class RegisterApiView(generics.GenericAPIView):
    """Creates new user with the given info and credentials"""

    serializer_class = RegisterSerializer

    def post(self, request, *args, **kwargs):
        """
        Register class
        """
        serializer = RegisterSerializer(data=request.data, many=False)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

core/accounts/views.py
# from django.shortcuts import redirect, render
from django.shortcuts import redirect
from django.contrib.auth.views import LoginView
from django.views.generic import FormView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth import login


# Create your views here.
class SignInView(LoginView):
    template_name = "accounts/signin.html"
    fields = "username", "password"
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy("todo:task_list")


class SignUpView(FormView):
    template_name = "accounts/signup.html"
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy("todo:task_list")

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(SignUpView, self).form_valid(form)

    # receive single object
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect("todo:task_list")
        return super(SignUpView, self).get(*args, **kwargs)

core/templates/accounts/signin.html
{% extends 'base.html' %}

{% block title %} SignIn {% endblock %}

{% block extra_css %}
<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
</style>
<link href="https://getbootstrap.com/docs/5.1/examples/sign-in/signin.css" rel="stylesheet">
{% endblock %}


{% block content %}
<main class="form-signin text-center">
    <form action="{% url 'accounts:signin' %}" method="POST">
        <a href="https://github.com/Abolfazlms"><img class="mb-4 rounded-circle border-3 border-white shadow p-1 mb"
                src="https://media.licdn.com/dms/image/v2/D4D03AQEZlmclGPHbaQ/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1692170540926?e=1729123200&v=beta&t=txZH3mwRlUF78QEquNGHIWjHdcHtFwMlZwkEKi9KGyE"
                alt="" width="150" height="150"></a>
        <h1 class="h3 mb-3 fw-normal">Please Login</h1>
        {% csrf_token %}
        <div class="form-floating">
            <input type="username" name="username" class="form-control" id="floatingInput"
                placeholder="name@example.com">
            <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Password</label>
        </div>

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Login</button>
        <p class="mt-3 mb-2">Dont have an account then <a href="{% url 'accounts:signup' %}">create one</a></p>
        <p class="mt-5 mb-3 text-muted">&copy; 2024-2025</p>
    </form>
    {% if form.errors %}
    <div class="alert alert-error">
        <h6>Please fix the following errors</h6>
        <ul>
            {% for field in form %}
            {% if field.errors %}
            {% for error in field.errors %}
            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
            {% endif %}
            {% endfor %}
        </ul>
        {% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% endif %}
    </div>
    {% endif %}
</main>
{% endblock %}

core/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %} SignUp {% endblock %}

{% block extra_css %}
<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
</style>
<link href="https://getbootstrap.com/docs/5.1/examples/sign-in/signin.css" rel="stylesheet">
{% endblock %}


{% block content %}
<main class="form-signin text-center">
    <form action="{% url 'accounts:signup' %}" method="POST">
        <a href="https://github.com/Abolfazlms">
            <img class="mb-4 rounded-circle border-3 border-white shadow p-1 mb"
                src="https://media.licdn.com/dms/image/v2/D4D03AQEZlmclGPHbaQ/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1692170540926?e=1729123200&v=beta&t=txZH3mwRlUF78QEquNGHIWjHdcHtFwMlZwkEKi9KGyE"
                alt="" width="150" height="150"></a>
        <h1 class="h3 mb-3 fw-normal">Please signup</h1>
        {% csrf_token %}
        <div class="form-floating">
            <input type="username" name="username" class="form-control" id="floatingInput"
                placeholder="name@example.com">
            <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password1" class="form-control mb-0" id="floatingPassword"
                placeholder="Password">
            <label for="floatingPassword">Password</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password2" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Repeate Password</label>
        </div>


        <button class="w-100 btn btn-lg btn-primary" type="submit">signup</button>
        <p class="mt-3 mb-2">Already have an account then <a href="{% url 'accounts:signin' %}"> login</a></p>
        <p class="mt-5 mb-3 text-muted">&copy; 2024-2025</p>
    </form>
    {% if form.errors %}
    <div class="alert alert-error">
        <h6>Please fix the following errors</h6>
        <ul>
            {% for field in form %}
            {% if field.errors %}
            {% for error in field.errors %}
            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
            {% endif %}
            {% endfor %}
        </ul>
        {% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% endif %}
    </div>
    {% endif %}
</main>


{% endblock %}