core/accounts/urls.py
from django.urls import path, include
from .views import SignInView, SignUpView

from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    path("signin/", SignInView.as_view(), name="signin"),
    path("logout", LogoutView.as_view(next_page="signin/"), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("api/v1/", include("accounts.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import include, path

# api documenting
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


# app urls
urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("todo.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

core/todo/api/v1/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

app_name = "api-v1"
router = DefaultRouter()
router.register("todo", views.TaskListViewSet, basename="todo")
router.register("task-detail", views.TaskDetailViewSet, basename="task-detail")
router.register("weather", views.WeatherViewSet, basename="weather-api")
# urlpatterns = router.urls

urlpatterns = [
    path("weather/", views.WeatherViewSet.as_view({"get": "retrieve"}), name="weather"),
    path("", include(router.urls)),
]

# urlpatterns = [
#     path('todo/',views.TaskListViewSet, name='todo-view'),
#     path('todo/<int:id>',views.TaskListViewSet,name='model')
# ]
# router.register('category',views.CategoryModelViewSet,basename='category')

core/todo/urls.py
from django.urls import include, path
from .views import TaskList, TaskCreate, TaskComplete, TaskUpdate, TaskDelete

app_name = "todo"

urlpatterns = [
    path("", TaskList.as_view(), name="task_list"),
    path("create/", TaskCreate.as_view(), name="create_task"),
    path("update/<int:pk>/", TaskUpdate.as_view(), name="update_task"),
    path("complete/<int:pk>/", TaskComplete.as_view(), name="complete_task"),
    path("delete/<int:pk>/", TaskDelete.as_view(), name="delete_task"),
    path("api/v1/", include("todo.api.v1.urls")),
]

core/todo/models.py
from django.db import models
from django.contrib.auth import get_user_model


# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(
        get_user_model(), null=True, blank=True, on_delete=models.CASCADE
    )

    title = models.CharField(max_length=250)
    is_complete = models.BooleanField(default=False)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateField(auto_now=True)

    class Meta:
        order_with_respect_to = "user"

    def __str__(self):
        return self.title

core/todo/forms.py
from django import forms
from todo.models import Task


class TaskForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control rounded-4",
                "name": "title",
                "placeholder": "enter the title",
            }
        ),
        label="",
    )

    class Meta:
        model = Task
        fields = ("title",)

core/todo/api/v1/views.py
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework import viewsets
from .serializer import TaskSerializer
from todo.models import Task

import requests
from django.core.cache import cache
from django.conf import settings
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie


class TaskListViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    permission_classes = [IsAuthenticated]

    def list(self, request):
        queryset = self.get_queryset()
        serializer = TaskSerializer(queryset, many=True)
        return Response(serializer.data)

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(user=self.request.user)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class TaskDetailViewSet(viewsets.ModelViewSet):
    serializer_class = TaskSerializer
    permission_classes = [IsAuthenticated]

    lookup_field = "task_id"

    def get_object(self, queryset=None):
        object = Task.objects.get(pk=self.kwargs["task_id"])
        return object

    def delete(self, request, *args, **kwargs):
        task = self.get_object()
        task.delete()
        return Response({"detail": "Task successfully deleted."})

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)

    def post(self, request, *args, **kwargs):
        task = self.get_object()
        serializer = TaskSerializer(data=request.data, instance=task, many=False)
        if serializer.is_valid():
            serializer.save()
        return Response(serializer.data)


class WeatherViewSet(viewsets.ViewSet):
    permission_classes = [IsAuthenticated]

    @method_decorator(cache_page(60 * 20))  # seconds * number
    @method_decorator(vary_on_cookie)
    def retrieve(self, request):
        city = "Tehran"
        cached_data = cache.get(f"weather_data_{city}")
        if cached_data:
            return Response(cached_data)

        api_key = settings.OPENWEATHER_API_KEY
        url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric"
        response = requests.get(url)

        if response.status_code == 200:
            data = response.json()
            cache.set(f"weather_data_{city}", data, timeout=60 * 20)
            return Response(data)
        else:
            return Response({"error": "Could not retrieve weather data"}, status=500)

core/todo/views.py
from django.shortcuts import redirect
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Task
from .forms import TaskForm

from django.urls import reverse_lazy


# Create your views here.
class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "todo/list_task.html"

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ["title"]
    success_url = reverse_lazy("todo:task_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskComplete(LoginRequiredMixin, View):
    model = Task
    success_url = reverse_lazy("todo:task_list")

    def get(self, request, *args, **kwargs):
        object = Task.objects.get(id=kwargs.get("pk"))
        object.is_complete = True
        object.save()
        return redirect(self.success_url)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task_list")

    template_name = "todo/update_task.html"


class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    content_object_name = "task"
    success_url = reverse_lazy("todo:task_list")

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

core/templates/todo/list_task.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Todo List {% endblock %}
{% block extra_css %}{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-5 shadow">
      <div class="modal-header p-5 pb-4 border-bottom-0">
        <!-- <h5 class="modal-title">Modal title</h5> -->
        <h2 class="fw-bold mb-0">Todo App</h2>
        <a type="button" class="btn-close" href="{% url 'accounts:logout' %}"></a>
      </div>

      <div class="modal-body p-5 pt-0">

        <form class="pt-3" method="POST" action="{% url 'todo:create_task' %}">
          {% csrf_token %}
          <div class="input-group mb-3">
            <input type="text" class="form-control rounded-4" name="title" placeholder="Enter task title"
              aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-primary" type="submit">Add</button>
          </div>


          <hr class="my-4">
          {% for task in tasks %}
          <div class="input-group py-1">
            <span type="text" class="form-control" aria-label="Text input with segmented dropdown button">
              {% if task.complete == True %}
              <strike>{{task.title}}</strike>
              {% else %}
              <span>{{task}}</span>
              {% endif %}
            </span>
            <a type="button" class="btn btn-danger" href="{% url 'todo:delete_task' task.id %}"><i
                class="bi bi-trash"></i></a>
            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split"
              data-bs-toggle="dropdown" aria-expanded="false">
              <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><a class="dropdown-item" href="{% url 'todo:complete_task' task.id %}">Done</a></li>
              <li><a class="dropdown-item" href="{% url 'todo:update_task' task.id %}">Edit</a></li>
            </ul>
          </div>

          {% endfor %}
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}{% endblock %}

core/templates/todo/update_task.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Edit Task {% endblock %}
{% block extra_css %}
{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
	<div class="modal-dialog" role="document">
		<div class="modal-content rounded-5 shadow">
			<div class="modal-header p-5 pb-4 border-bottom-0">
				<!-- <h5 class="modal-title">Modal title</h5> -->
				<h2 class="fw-bold mb-0">Edit Form</h2>
				<a type="button" class="btn-close" href="{% url 'todo:task_list' %}"></a>
			</div>

			<div class="modal-body p-5 pt-0">

				<form method="POST" action="">
					{% csrf_token %}
					<div class="form-floating mb-3">
						{{form}}
						<label for="floatingInput">Title</label>
					</div>
					<button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Change</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block extra_js %}{% endblock %}

<div class="header-bar">
	<a href="{% url 'todo:tasks' %}">&#8592; Back</a>
</div>


<div class="card-body">
	<form method="POST" action="">
		{% csrf_token %}
		{{form.as_p}}
		<input class="button" type="submit" value="Submit">
	</form>
</div>